disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
  - control_statement
  - trailing_whitespace
  - unused_optional_binding
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  warning: 140
  error: 280
  ignores_comments: true
  ignores_urls: true
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: 4
  max_length: 40
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey

